### ISSUE TITLE
jar?

### ISSUE THREAD

**Issue by Serega007RU** [hugmanrique/NoWorldSave#1]
Where are jar file?

**Comment by hugmanrique** [comment]
Please clone this repo with git and run `mvn package`. You will find the built jar file on the `target` directory.

**Comment by Serega007RU** [comment]
Thank you, I already realized that I will have to spend time installing
maven, then wait a long time for it to download a million libraries,
compile the plugin, and only at the end realize that this plugin does not
work. Thank you for my time and nerves, was it really so difficult to throw
a jar in realeses?

чт, 11 февр. 2021 г., 02:32 Hugo Manrique <notifications@github.com>:

**Comment by hugmanrique** [comment]
Cry me a river.
